import type { Metadata } from "next";
import "./globals.css";
import vazirmatnFont from "@/constants/localFonts";
import AppProvider from "./providers/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirmatnFont.variable} font-vazirmatn`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
